### ISSUE TITLE
AOS not working without anchor placement

### ISSUE THREAD

**Issue by mariodermez** [michalsnik/aos#352] opened 2018-06-23 22:36 UTC
I really don't get what's wrong with the code. I've done everything correctly and the code is only working if I put an anchor-placement. It doesn't work without it.  So what's the deal with the anchor placement? Why I can't have the code without the anchor?

**Comment by mariodermez** [comment] 2018-06-24 20:06
I tried most of your recent versions. The one I had and the ones you're using online. 
Nothing is working. I have to add a anchor placement in order for the eg. fade-up to animate. 

This is my script: 
`        <script src="../assets/js/aos.js"></script>
    <script>
        AOS.init({
                easing: 'ease-in-out-sine'
              });
        window.addEventListener('load', AOS.refresh)

    </script>`

And here is the call: 
```
<div class="content-grid-item" data-aos="fade-up" data-aos-anchor-placement="top-center">
                                    <figure class="fig cover" style="background-image:url(*******);"><img src="../images/image.jpg" ></figure>
                                </div>
```
I have to use the anchor placement in order to animate. Why this happens? 
FYI. I don't know if I added your additional code correctly. I tried even adding it in another script.

**Comment by mariodermez** [comment] 2018-06-24 20:14
Is a video going to help you? I can send it directly to your email.

**Comment by michalsnik** [comment] 2018-07-07 16:37
Video might help, but please also show what other styles does `.content-grid-item` element have, perhaps something's messing calculations. It might also be caused by parent elements' styles somehow. Can you reproduce this issue on codepen?

**Comment by michalsnik** [comment] 2018-10-03 23:56
It's been some time since the last message here - I'm going to close it, but please feel free to reopen this issue @mariodermez if you have more informations.

**Closed by michalsnik** 2018-10-03 23:56 UTC
Labels: question, unconfirmed

**Comment by Derricknjoroge** [comment] 2019-06-10 08:32
> Please make sure you initialize AOS after DOM has been rendered. You might also want to try adding the following code:
> 
> ```
> window.addEventListener('load', AOS.refresh)
> ```
> 
> Let me know if that helps. Also what version of AOS are you using currently?

This worked for me! Thank you!
