### ISSUE TITLE
Animate-Once

### ISSUE THREAD

**Issue by anshap1719** [michalsnik/aos#33] opened 2016-07-05 06:22 UTC
I want to fade-in my elements when they are in view but i want them not to fade out whatsoever. How can I achieve this?

**Comment by michalsnik** [comment] 2016-07-05 06:25
Hi, check out 'once' option in readme. I tried to explain there all possible settings.

**Comment by anshap1719** [comment] 2016-07-05 10:14
I did, but its not working. Sorry.

**Comment by michalsnik** [comment] 2016-07-05 11:00
@anshap1719 please prepare simple codepen that illustrates your issue, I'll review it and then will be able to fix it sooner :)

**Comment by uniqe15** [comment] 2016-07-05 12:24
I have other problem with "data-aos-once" i did set it set to false on all elements and they are not fading out after i scroll down and then up

**Comment by michalsnik** [comment] 2016-07-05 15:30
I tried to reproduce those issues, however "it works for me".
Please prepare simple codepen example that shows this issue, it would be very helpful.

You can fork my codepen example and modify to reproduce bug: http://codepen.io/michalsnik/pen/WxNdvq

Looking forward to hearing from you @uniqe15 @anshap1719

**Comment by Randore** [comment] 2016-07-24 11:55
@uniqe15 : by default the **data-aos-once** is set to false so you don't have to add that.
@anshap1719 : This is how you have to write the markup to make the elements work only once.
Example:
`<div class="item" data-aos="zoom-in" data-aos-once="true">
      5
</div>`

**Comment by michalsnik** [comment] 2016-08-20 19:31
Did @Randore answered your question @anshap1719 ? I'm closing this issue for now as it seems like there's no issue with this. Feel free to reopen this when you'll have time to prepare an example that would present your problem.

**Closed by michalsnik** 2016-08-20 19:31 UTC
Labels: unconfirmed
