### ISSUE TITLE
Script for Wordpress

### ISSUE THREAD

**Issue by Ricco-S** [michalsnik/aos#142] opened 2017-04-18 08:21 UTC
No Animation in Wp 
I think the problem is the script

**Comment by wkjones** [comment] 2017-04-22 14:27
I just used this in a WP project. Make sure after you load the JS and CSS you add.

<script>
    AOS.init();
</script>

It should work just fine.

**Comment by netes** [comment] 2017-04-27 17:53
It works like a charm in Wordpress, definitely you're doing something wrong.

**Comment by mmason33** [comment] 2017-06-27 18:33
Agreed I utilize this library in Wordpress as well. Check your cdn scripts and links.

**Comment by michalsnik** [comment] 2017-07-07 01:43
I'm closing this issue. It looks like it's not a problem with AOS itself. I'm glad it works for you guys :)

**Closed by michalsnik** 2017-07-07 01:43 UTC

**Comment by helloromero** [comment] 2018-11-16 17:48
I am having this issue. I use it all the time in none WP projects but for some reason it just doesn't work in WP. The classes `aos-init aos-animate` are added on the elements but nothing happens. Super weird.

**Comment by helloromero** [comment] 2018-11-19 11:49
For anyone else having this issue if you're developing theme's using a shell theme like html5blank make sure you remove no-js from `<html class="no-js">` as adding no-js stops the animation from working. `no-js` is used for displaying websites differently for people who do not have JS enabled and this class is also used in the aos to stop animations from working.

**Comment by latheeshvm** [comment] 2018-11-25 17:29
> For anyone else having this issue if you're developing theme's using a shell theme like html5blank make sure you remove no-js from `<html class="no-js">` as adding no-js stops the animation from working. `no-js` is used for displaying websites differently for people who do not have JS enabled and this class is also used in the aos to stop animations from working.

You saved my day!! thank you

**Comment by ortonomy** [comment] 2019-10-16 08:01
@helloromero -- oh my word, you saved my day. I was having such an annoying time with this! And this was exactly the cause. 

Why does AOS have a dependency on Modernizr??!?!?

https://stackoverflow.com/questions/6724515/what-is-the-purpose-of-the-html-no-js-class

**Comment by joshangehr** [comment] 2019-10-16 13:55
@ortonomy It's not a dependency on Modernizr, [it prevents invisible elements when JS is disabled](https://github.com/michalsnik/aos/blob/next/src/sass/_animations.scss). The class is used to detect whether or not JS is enabled, and whichever theme you're using should convert the root class to `js` on load.

**Comment by ortonomy** [comment] 2019-10-16 14:10
@joshangehr - I know what and how the ‘no-js’ / ‘js’ classes are used, Modernizr or WP dependency, doesn’t matter, it’s still a dependency on an (arguably anachronistic) non-standard way of deciding whether to apply the animations or not. 

I’m not sure it has a place in AoS.

**Comment by joshangehr** [comment] 2019-10-16 23:12
But in this case it's not "deciding whether to apply the animations or not", it's integrating a common pattern to _prevent_ the elements [rendering invisible](https://github.com/michalsnik/aos/issues/81#issuecomment-299169672) when JS in unavailable: this way the page content is still readable and indexable by search engines.

The only reason it has a place in AOS is because of how often it's been discussed. I do agree that it should be outlined in the documentation a bit better, but if a framework adds a `no-js` class to the root element without replacing it, this seems like a failure on the part of the framework.

The `noscript` approach linked above works just as well if you'd rather go that route, considering `@next` is still in beta. I'm still using this on most builds.

All this said though, I do wonder if the `no-js` class is the best approach. Maybe it's something that should happen by default in the `AOS.init()` initialization.

**Comment by ortonomy** [comment] 2019-10-17 06:29
@joshangehr -- got it. Yes, my intimated reason for existence was incorrect, but my objection still stands. ``no-js`` ``js``  creates a tightly-coupled dependency on something that is not really standard (despite being once widespread and slowly forgotten and arguably even unnecessary. (very very few devices will have JS turned off except of course for search engine indexes (although many of them now use and execute JS environment.). We really really shouldn't be relying on some other framework or lib to 'enable' to add or replace classes that can break this lib.

As far as I can tell, ``no-js`` *is* something that was implemented almost exclusively by modernizr as part of its feature detection lib. (which is included in WP + themes)

>  I do agree that it should be outlined in the documentation a bit better

not just documented but left up to the user to decide if they want this particular feature 

> If you want to maximise SEO friendliness, make sure to load your page with a ``no-js`` class on the html tag. This way, AOS will not hide any elements tagged as animatable when visited by web crawlers and bots, or in environments where JS is not available.

Or **even better**, don't mix AOS at ALL with some other external libs feature detection. 

> If you want to maximise SEO friendliness, make sure to load your page with a ``no-aos`` class on the html tag. This way, AOS will not hide any elements tagged as animatable when visited by web crawlers and bots, or in environments where JS is not available. **Ensure your custom scripts remove the ``no-aos`` class or the AOS animations will not run.** NB: The ``no-aos`` class can be put on any ancestor element that you wish to SEO optimize. Remember to remove it to make sure AOS CSS can be applied.

**Comment by contriveitup** [comment] 2020-08-02 19:37
> For anyone else having this issue if you're developing theme's using a shell theme like html5blank make sure you remove no-js from `<html class="no-js">` as adding no-js stops the animation from working. `no-js` is used for displaying websites differently for people who do not have JS enabled and this class is also used in the aos to stop animations from working.

This also saved my day. Thought at first, here goes another day debugging an issue which is working absolutely fine in a non-WP (HTML) Theme.

**Comment by firverrwrok0** [comment] 2020-10-18 08:47
I made it the right way. I have used AOS in my Divi wordpress. Here you can see the site: https://ntechway.com/
