### ISSUE TITLE
Text shadow (or color, or weight) different with AOS enabled

### ISSUE THREAD

**Issue by crnkovic** [michalsnik/aos#39] opened 2016-07-26 23:44 UTC
This is font without AOS enabled:

![Image](http://image.prntscr.com/image/ba8facbe932740bbb389a5ea1e753f30.png)

This is font with AOS enabled:

![Image](http://image.prntscr.com/image/697a9c01e7aa4566b66f4f79a97b0a5b.png)

As you can see, font shadow is a bit different, not sure why.

**Comment by michalsnik** [comment] 2016-07-28 07:54
Hi @crnkovic 
Do you have working example maybe? If you'll provide me with codepen or smth I'll be able to investigate this issue. AOS styles shouldn't interfere with this. It's probably caused by transforms, is this problem replicable on different browsers or only this one you use?

**Comment by LucaRosaldi** [comment] 2016-08-11 14:18
Looks like a font-smoothing issue related to hardware acceleration.

Try setting a specific `-webkit-font-smoothing` in your CSS. This should solve the problem.

**Comment by michalsnik** [comment] 2016-08-20 19:28
I think this might be the case. For now I'm closing this issue @crnkovic . Feel free to open this again when you prepare an example that would present this issue.

**Closed by michalsnik** 2016-08-20 19:28 UTC
Labels: question, unconfirmed
