### ISSUE TITLE
Firefox: Scroll freezes at page load

### ISSUE THREAD

**Issue by BrunoCartier** [michalsnik/aos#221] opened 2017-09-17 22:58 UTC
Hey,

First of all, awesome lib, very easy to set up 👍 

I am using it for a project, and I have the following issue:
When AOS is activated, using Firefox, the page loads, then the scroll freezes for a second or two, then it comes back. This is really annoying.

I first tough it was related to my own JS code, but it is not, since I have the same issue on the [demo website](http://michalsnik.github.io/aos/).

Any idea where it comes from, or how to solve it?

Firefox version: 55.0.3
Platform: Windows 7
(no problem with Chrome)

**Comment by michalsnik** [comment] 2018-06-21 21:57
Hey @BrunoCartier. Unfortunately I couldn't reproduce this issue. Has anyone got this problem too?

**Comment by michalsnik** [comment] 2018-07-08 16:19
Given that no one else reported this problem for the past year I'm going to close this issue and assume that it's working properly now.

**Closed by michalsnik** 2018-07-08 16:19 UTC
Labels: bug, unconfirmed
