### ISSUE TITLE
AOS isn't working at all.

### ISSUE THREAD

**Issue by mtyrio** [michalsnik/aos#67] opened 2016-10-15 08:16 UTC
I'm trying to implement aos but it seems broken.
Here is HTML and CSS.
`<!DOCTYPE HTML>
<html lang="pl">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	
	<title></title>
	
	<meta name="" content="" />
	<meta name="keywords" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="style.css" type="text/css" />
	<link href="https://cdn.rawgit.com/michalsnik/aos/2.0.4/dist/aos.css" rel="stylsheet">
	<script src="https://cdn.rawgit.com/michalsnik/aos/2.0.4/dist/aos.js"></script>	
	<script>
		AOS.init();
	</script>
</head>
<body>
	<div class="item" data-aos="fade-up">1</div>
	<div class="item" data-aos="fade-down">2</div>
	<div class="item" data-aos="fade-right">3</div>
	<div class="item" data-aos="fade-left">4</div>

	<div class="item" data-aos="zoom-in">5</div>
	<div class="item" data-aos="zoom-out">6</div>

	<div class="item" data-aos="slide-up">7</div>

	<div class="item" data-aos="flip-up">8</div>
	<div class="item" data-aos="flip-down">9</div>
	<div class="item" data-aos="flip-right">10</div>
	<div class="item" data-aos="flip-left">11</div>
</body>
</html>
`
`* {
  box-sizing: border-box;
}

.item {
  width: 200px;
  height: 200px;
  margin: 50px auto;
  padding-top: 75px;
  background: #ccc;
  text-align: center;
  color: #FFF;
  font-size: 3em;
}`

It has been taken from Live Demos at https://css-tricks.com/aos-css-driven-scroll-animation-library/, I just copied it but it's not working, I'm beginner front-end so i would be glad for an working answear.

**Comment by Shouriums** [comment] 2016-10-17 18:46
I also couldn't get it to work neither downloading the files or the CDN. I checked on the files of the codepen and got this cdns that worked well:

<link rel="stylesheet" href="https://cdn.rawgit.com/michalsnik/aos/2.0.1/dist/aos.css">
<script src="https://cdn.rawgit.com/michalsnik/aos/2.0.1/dist/aos.js"></script>

IDK if there's a bug on version 2.0.4 but couldn't get it to work.

**Comment by michalsnik** [comment] 2016-10-20 18:50
Hi, provided demos were using 2.0.4 and they are using perfectly fine. Current version however is `2.1.1` please check it out, and make sure you initialize `AOS` once `body` is in the DOM. The easiest way to assure this is to initialize AOS just before `</body>` tag. I'm closing this for now as I'm not able to reproduce those issues. Everyting seems to be working fine.
Feel free to prepare demos on codepen that will illustrate your problems and I'll help you fix it then :)

**Closed by michalsnik** 2016-10-20 18:50 UTC

**Comment by sharden** [comment] 2016-11-19 20:37
I had a similar issue but was able to resolve. If you're reading this and used the provided CDN's please read.

Crack open inspect element in your browser and do the following: 

Check the DOM element where you added data-aos="blah" and scroll. If JS is loaded you'll see the class names change dynamically. If that works, your JS file is good but your css may be missing.

Select Sources to verify 'cdn.rawgit.com/michalsnik/aos/2.*(version you're on) is there and loads both aos.js and aos.css. My css didn't load even using the provided CDN so I manual placed the css file.

Hope this helps.

**Comment by pietrofxq** [comment] 2016-11-29 20:53
The problem is that in the docs, the css <link>tag has rel="stylsheet" which makes the css not to load. You need to fix it to "stylesheet"
