### ISSUE TITLE
elements disappear when I add the data-aos code! 

### ISSUE THREAD

**Issue by ferretl** [michalsnik/aos#239] opened 2017-10-29 10:41 UTC

**Comment by ferretl** [comment] 2017-10-29 10:50
every time I put the code in the elements disappear.
here is an example 
`<div class="content" data-aos="fade-right">`
my content disapeers 
`<div class="content>`
everything stays there

**Comment by Seculin** [comment] 2017-10-30 11:54
for me too, seems like latest update brought in some bug?

**Comment by Operator21** [comment] 2017-11-04 18:08
Same here.

**Comment by ferretl** [comment] 2017-11-05 04:02
do i put AOS.init that is my script tag?

**Comment by goragag** [comment] 2017-11-11 22:27
The same thing happened here. New to AOS. I did everything under the rules:

1. Linked the CSS file
2. Linked the JS file
3. Initialized the AOS at the end of the body

```
<script src="assets/js/aos.js"></script>
<script>
AOS.init();
</script>
</body>
```
4. Added the data-aos tag to the DIV element.
`<div class="content" data-aos="fade-up">`

Anyone have an idea how to fix that issue, @Operator21 @michalsnik?

**Comment by goragag** [comment] 2017-11-11 22:44
Edit: The animation seems like is working now.

Though, couple of days ago the HTML had quite strange behaviour. First, the animation didn’t worked. Then I added the data-aos-delay tag and one worked. Then I removed data-aos-delay and animation again worked. The next day when I opened the website, not only the animation didn’t worked, but also the DIV element was not displayed.

Strange. I hope everything will remain satisfactory.

**Comment by bfan1256** [comment] 2018-01-12 04:41
Maybe try loading the `aos.js` in the `<head></head>` and then initializing at the end of the body.
```html
<head>
    <script src="assets/js/aos.js"></script>
</head>
<body>
    <div data-aos="fade-up">
         Hello
    </div>
    <script>
        AOS.init();
    </script>
</body>
```

**Comment by goragag** [comment] 2018-01-12 11:31
@bfan1256 Thank you. Now AOS works fine. Though I'll write down somewhere your suggestion.

**Comment by bfan1256** [comment] 2018-01-12 12:18
Great! I'm glad AOS works for you! It acts very weird sometimes!

**Comment by bfan1256** [comment] 2018-01-12 12:18
Great! I'm glad AOS works for you! It acts very weird sometimes!

**Comment by ebruin22** [comment] 2018-02-06 03:54
My elements are also disappearing. I added the CSS and JS CDN links in my header and initialized as <script> AOS.init(); </script> right before my closing body tag. But my element don't show up. Please help

**Comment by bfan1256** [comment] 2018-02-07 21:32
@ebruin22 , could you show some more information?

**Comment by michalsnik** [comment] 2018-05-17 22:02
Hi there! Please try to add:
```
window.addEventListener('load', AOS.refresh)
```
It should solve all your issues. Sometimes `DOMContentLoaded` event is just too early to initialize AOS, because some images that we load might change positions of our elements on the page, and AOS then might not recalculate their trigger points.

You can also just use `startEvent: 'load'` seeting instead of adding additional listener.

If this problem will still occur for you please reopen this issue and provide more informations, that would allow us to debug it properly :)

**Closed by michalsnik** 2018-05-17 22:02 UTC

**Comment by Raghav-Kumar-Jha** [comment] 2018-08-13 18:35
this is not working in my real project, the same hidden problem comes again and again. I have tried all the possible ways to initialise it. But it is still not working for me.

**Comment by ryanrocket** [comment] 2019-07-24 01:37
I am having the same issue

**Comment by alaa19090** [comment] 2020-12-21 08:59
the problem is the `overflow` property  in any container tag and the important one is HTML and body

**Comment by alaa19090** [comment] 2020-12-21 09:02
the problem is the `overflow` property  in any container tag and the important one is HTML and body you have to cancel it and fix your problem

**Comment by stephanieraymos** [comment] 2021-01-03 05:19
I'm having the same issue. Have tried every recommendation in these comments and not solved. My elements are there on small screens but with larger screens both disappear and do not load/show up at all on refresh with larger sizes.

**Comment by stephanieraymos** [comment] 2021-01-03 05:40
I removed the offset and duration from my init and it works now

**Comment by Carlosm99** [comment] 2021-01-29 05:14
@bfan1256 It works. Thanks, man! really appreciate it.

**Comment by Basir-PD** [comment] 2021-05-18 12:33
I couldn't solve it either, I tried all different approaches and end up frustrated and creating my own simple library

**Comment by gAusWeb** [comment] 2022-02-11 08:59
My issue only happened in Firefox, so adding the missing Firefox Browser Prefixes solved my issue. 

I did this by ditching the pre-compiled vendor CSS that comes with the NPM package, an imported the AOS.scss master import file from the NPM package into my solution instead, where I am using postCss & [postcss/autoprefixer] (https://github.com/postcss/autoprefixer) to add the missing Firefox browser prefixes. 

Bonus tip - for those using sticky nav's, instead of placing the `overflow: hidden;` on the `html, body {}` tags, wrap only the area(s) that are animated in a wrapping container (I used a `<section class="section--animated" />` wrapper) that spans the full width of the screen (direct children of the `body` is one example of this) and apply the `overflow:hidden;` to that unique class, instead. This will allow fixed position elements to behave as per normal.

**Comment by achmalll** [comment] 2023-07-27 10:04
I still haven't found a solution to all of this😭😭

**Comment by Adhilc** [comment] 2024-04-18 06:55
> every time I put the code in the elements disappear. here is an example `<div class="content" data-aos="fade-right">` my content disapeers `<div class="content">` everything stays there

i found the same issue any solutions?

**Comment by b3nhard** [comment] 2025-01-06 22:31
Angular developers who use lazy loading of components must call AOS.refresh() on component initialization.
If you're using ssr ensure you run this inside afterNextRender to ensure it is run on the client side.
Happy coding!
