### ISSUE TITLE
AOS Won't Trigger if CSS has an overflow property besides visible.

### ISSUE THREAD

**Issue by thedakotabarron** [michalsnik/aos#52] opened 2016-09-18 12:44 UTC
I had some issues getting elements to trigger. I narrowed it down to the overflow property. It seems that if overflow is set and it's set to anything other than "visible", the element in question just doesn't display at all and certainly doesn't get triggered.

**Comment by michalsnik** [comment] 2016-09-21 22:13
Hi @thedakotabarron, 

I tried to recreate this issue, but with no luck. Setting overflow to whatever on the example `/demo/simple.html` doesn't cause any problems. If you could just create a codepen that will present this problem - it would be great.

For now I'm closing this, feel free to reopen when you'll prepare a `not working` example :)

**Closed by michalsnik** 2016-09-21 22:13 UTC

**Comment by thedakotabarron** [comment] 2016-09-22 12:43
Hello,

It's a very complicated site, so perhaps this won't be able to be resolved as I'm not able to create a codepen demonstrating the issue.

You can view the site here (without AOS set up): http://nosilencemedia.com

You can also view the site here (with AOS set up and the element that talks about "creation" on the services page with a fade-left tag applied): http://nosilencemedia.com/new

I don't know if this will help in any way, but hopefully you might be able to figure something out from the browser inspector.

Thank you,

Dakota

**Comment by Madebym** [comment] 2016-11-09 22:01
I can confirm the same behaviour. 

I normally wrap all of my page elements inside one main container and give that container `overflow-x: hidden`, because  iOS devices tend to create horizontal scrollbar if any animations are taking place.

Doing this with AOS was causing it to not trigger at all. That is when I moved `overflow-x: hidden`  to `body`, but still no AOS triggering.

Only after I moved it to `html` element, I got the AOS to trigger, and no horizontal scrollbars on Android  and iOS.

**Comment by thedakotabarron** [comment] 2016-11-09 22:08
That's interesting. So in the css, make the overflow property parts of the html element? I'll see if that works for me. Thank you for the input.

**Comment by Madebym** [comment] 2016-11-09 22:26
Yep, it worked for me. I normally do it on the main page wrap element, but moving it to html worked.

**Comment by thedakotabarron** [comment] 2016-11-09 23:02
It semi worked for me... Putting on the html element worked in the sense that AOS triggers and everything still is aligned and displays properly and such... 

However, there is a lot of extra space at the bottom of all the pages except for "services". Services is the longest page and all the other pages seem to be the same length even though there is no content to fill them.

Here you can view the current live site without AOS and how the pages should display: http://nosilencemedia.com

Here you can view the same site, but with the tweaks made to enable and allow AOS to trigger. On the services page, the "creation, conversation, completion" bit fades in... But you can also see the extra space on all the pages: http://nosilencemedia.com/new

Anyone have any ideas?

**Comment by Madebym** [comment] 2016-11-11 23:39
I've had a quick look, maybe it is due to setting AOS on the body element. You have .pt-page class applied to some elements, maybe it is being displayed due to AOS being on the body.

Have you tried it on some other elements?
