### ISSUE TITLE
background color issue

### ISSUE THREAD

**Issue by jiachunkang** [michalsnik/aos#31] opened 2016-06-27 15:19 UTC
Hi,

I have issue if the div have background color.

If the div background color is #fff, it dont have issue.
If the div background color is grey, it will have overlay issue appear.
Please refer to screenshot. 
![screenshot_1](https://cloud.githubusercontent.com/assets/20169837/16384969/9e6dc5ba-3cbd-11e6-90d4-7eed7ce18bb6.jpg)

May I know how can I fix this by CSS? 

THanks

**Comment by jiachunkang** [comment] 2016-06-27 15:20
You can see the first navigator (can show completely).

The second navigator only can see half, due to the next div have background color.

**Comment by michalsnik** [comment] 2016-06-27 23:27
Hi @jiachunkang, unfortunately screenshot doesn't tell me much, and this can be caused by many things, it even can have nothing to do with AOS. CodePen with working example would be very helpful in this case.
I can't see on the screenshot which elements are using AOS, which are not, what kind of animations are applied etc.

I'm closing this issue right now, if you'll prepare CodePen example feel free to reopen it, and make sure this issue only appears when AOS is on :)

**Closed by michalsnik** 2016-06-27 23:27 UTC

**Comment by jiachunkang** [comment] 2016-06-28 02:10
sorry about that.
By the way, I found the way to solve this issue. 
I put data-aos at inner div

Thank you for your AOS. it awesome.
