### ISSUE TITLE
Change 2D transforms in favor of 3D transforms

### ISSUE THREAD

**Issue by gerardreches** [michalsnik/aos#186] opened 2017-07-05 11:04 UTC
Currently all the animations are using 2D transforms. They could have [improved performance](https://www.sitepoint.com/introduction-to-hardware-acceleration-css-animations/) using 3D transforms, which pushes CSS animations into hardware acceleration.

This allows smoother animations at the cost of some extra memory, this could be a problem in some mobile devices, but media queries can be used for that.

**Comment by michalsnik** [comment] 2017-07-06 23:04
Hey @gerardreches, current animations seem to be already really smooth even on mobile devices, but if you'd like to run a comparison and present the performance gain, you're free to go. If it proves to be a worthy change than I'll be more than happy to introduce it in this plugin :)

**Comment by rang501** [comment] 2018-05-11 08:03
I can confirm that the current animations are not smooth enough, they are way smoother with wow.js and animate.css, it is really noticeable on mobile devices (I have mid-range device). Tried different easings but it didn't help.
Might be caused by the content I use, but if the wow.js can animate same items smoother, then I guess there are some ways to improve AOS.

**Comment by michalsnik** [comment] 2018-05-14 22:26
I introduced translate3d and few performance optimisations in the upcoming v3: https://github.com/michalsnik/aos/tree/next
Beta will be released in few days

**Closed by michalsnik** 2018-05-14 22:26 UTC
Labels: enhancement
