### ISSUE TITLE
Resizing window breaks final animations on the page

### ISSUE THREAD

**Issue by julesforrest** [michalsnik/aos#134] opened 2017-03-30 17:59 UTC
On my project, if you load the page and then resize the window, the final elements of the page don't load at all. If you refresh and scroll down to the bottom, the elements load fine, so I don't think it's a problem with the height of the viewport or scrolling far enough to trigger the animation. Any ideas on how to fix?

**Comment by michalsnik** [comment] 2017-04-01 13:14
Maybe your elements are being positioned on window resize in some other way which causes them to be placed after AOS refreshes their position thus their position is miscalculated.

Make sure what happens to your elements on resize, are you delaying calculation of their positions or use some kind of grid script that manipulates theirs positions?

If you could prepare an example illustrating this issue, I might be able to help you. Right now my hands are tight. I think it's rather problem with your project, not directly with AOS.

**Comment by solancer** [comment] 2017-04-24 17:19
Even I'm sort of facing the same issue when I set the zoom level to 75%

document.body.style.zoom = '75%';
          AOS.init();
          
          setTimeout(function(){ 
            AOS.refreshHard();
          }, 3000);

**Comment by michalsnik** [comment] 2018-05-14 00:40
I'm closing this issue due to long overdue and inability to reproduce the problem.

**Closed by michalsnik** 2018-05-14 00:40 UTC
