### ISSUE TITLE
Page layout with javascript disabled

### ISSUE THREAD

**Issue by 033MaX** [michalsnik/aos#248] opened 2017-11-27 18:00 UTC
Hello,

AOS is pretty sweet library. But I'm facing an issue for websites that have to be compliant with accessibility standards. Besides loading myself the library manually with a document.write and initializing it, maybe AOS could implement a way to deal with this kind need.

Also it is exactly the same if the javascript happens to crash while loading. The page is unreadable.

**Comment by Dzordzu** [comment] 2017-12-06 19:08
I've got temporary solution for that. Just add following lines
```
  var AOSjsFriendly = {
    objects: document.getElementsByClassName("addAos"),
    init: function() {
      for(var i=0; i<this.objects.length; i++) {
        var obj = this.objects[i];
        var attr = obj.getAttribute("data-addAos");
        obj.setAttribute("data-aos", attr);
      }
    }
  }
  AOSjsFriendly.init();
```
Then to set AOS you need only two things:

1. Add .addAos class to the object on which you want AOS to act
2. Replace data-aos with the data-addAos attribute

Hope it will fix your problems.

**Comment by basicdays** [comment] 2018-03-22 06:19
The way I solved this is as follows:

On the html element, add a `no-js` class to it: `<html class="no-js">`

In the head section, add a script that removes the class. The reason I have this early is that I want that class removed as soon as possible for styling purposes. You'll probably want this before any other `script` tags, `style` tags, and `link` tags with external stylesheets.

```js
<script>document.documentElement.classList.remove('no-js');</script>
```

In your css, add the following style rule:

```css
:root.no-js [data-aos^=fade][data-aos^=fade] {
	opacity: 1;
	transform: none;
}
```

**Comment by Dzordzu** [comment] 2018-03-25 00:24
Oh I've forgotten to reference it

**Comment by Dzordzu** [comment] 2018-03-25 00:26
Possible duplicate of #190

**Comment by michalsnik** [comment] 2018-05-17 22:41
Hey @033MaX Thanks for posting this valid concern. However it's duplicate of #81 
I'm going to work on it soon :)

**Closed by michalsnik** 2018-05-17 22:41 UTC
