### ISSUE TITLE
scrolling relative to a div rather than the window/document?

### ISSUE THREAD

**Issue by gepetto503** [michalsnik/aos#253] opened 2017-12-15 07:31 UTC
See CodePen: https://codepen.io/gepetto503/pen/PEqxeo

I have two main divs, one with text, one with images.  On mobile/tablet, the text is on top and the images are below, as they appear in the markup.  you scroll down and the images animate in as expected.

However, when the browser is resized to desktop size, the div with the images moves to the right and scrolls separately from the text, so the text is fixed on the left while you scroll through the images on the right.  Now only the first image or two appears.  I'm assuming this is because the library uses the distance between the element and the top of the window, whereas in this case that distance is never reached because the body itself is not being scrolled, just the div with the elements.

Is there a way to change this?  I tried messing around with anchors but that didn't seem to be it.

Thanks in advance!

**Comment by michalsnik** [comment] 2018-05-17 22:49
Duplicate of #223 :)

**Closed by michalsnik** 2018-05-17 22:49 UTC
