### ISSUE TITLE
Not Working on IE 11

### ISSUE THREAD

**Issue by mkriha-23** [michalsnik/aos#123] opened 2017-03-16 01:38 UTC
![screenshot](https://cloud.githubusercontent.com/assets/26448124/23977741/61b9c0e8-09c6-11e7-8c90-3ba1fe132850.jpg)

I have a wordpress site that I am incorporating your AOS library into. I am having issues with the elements with AOS applied not showing up on IE 11 (it works fine on Edge). It doesn't look like the CSS is switching from opacity: 0; to opacity: 1; . I saw a ticket opened a few weeks ago with the same issue but it wasn't resolved. I am using your latest cdn version without any additional functions applied.

Also, I'd like to note that I pulled up your AOS "sample" page in IE 11 and there it is working fine..... ????

**Comment by michalsnik** [comment] 2017-03-16 09:45
Hey, that old issue was there for a few months and I didn't get any answer from it's creator so I closed it. It's good that you have a working example that replicated this issue. Let me check what's wrong. I'll get back to you with more informations soon.

**Comment by michalsnik** [comment] 2017-03-16 09:46
Ah it's about SVG.. Have you tried to add AOS on parent element instead of SVG itself? That might resolve your issue.

**Comment by michalsnik** [comment] 2017-03-16 10:01
I think the problem is that IE11 doesn't support CSS animations on SVGs. Wrap them in div and apply animation to div and everything should work as expected :) If this helps you please close this issue.

**Comment by mkriha-23** [comment] 2017-03-16 16:19
Thanks! This fixed it my issue.

Additional note: one other thing I noticed in IE is that the header animations housed in the viewport upon page load, which I want to render upon page load, don't render until the user starts to scroll. (Obviously animates in upon page load in every other browser I've tested, Edge included) 

In my own personal case, I've incorporated another css library for the logo and subtitle, but this is breaking on my rotating gears in the background because I have my animation iteration set to infinite, so therefore they are "infinitely" zooming in. This is minor (for one browser) in this example because these are supporting elements. I'm no developer :O, but maybe this is a relatively simple fix you could address in your next release?

Thanks for the great library!

**Closed** 2017-03-16 16:27 UTC
