### ISSUE TITLE
[Question] AOS + animate.css

### ISSUE THREAD

**Issue by Drewkan** [michalsnik/aos#295] opened 2018-03-07 06:01 UTC

**Comment by missmatsuko** [comment] 2018-03-14 02:14
What's the question?

**Comment by Drewkan** [comment] 2018-03-21 16:31
Sorry, i don't know what happened.

The question is if i can make AOS work easely with Animate.css somehow

**Comment by a-mojica** [comment] 2018-05-11 20:49
[ Duplicate of #7 ]
Hey @Drewkan, regarding your question, please see issue #7.

**Comment by michalsnik** [comment] 2018-05-15 22:33
Closing in favor of #7 
I just published proposition for the API that would allow to use any animation library with AOS :)

**Closed by michalsnik** 2018-05-15 22:33 UTC
